version: "3.9"

services:
  django:
    build: .
    container_name: django_app
    command: ["./scripts/start-django-otel.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=django-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - otel-collector

  # caddy:
  #   image: jaredlander/caddy-dns:duckdns-latest
  #   container_name: caddy_proxy
  #   platform: linux/amd64
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   env_file:
  #     - .env
  #   depends_on:
  #     - django
  #   restart: unless-stopped

  # celery:
  #   build: .
  #   container_name: celery_worker
  #   command: ["./scripts/start-celery-otel.sh"]
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   environment:
  #     OTEL_TRACES_EXPORTER: otlp
  #     OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  #     OTEL_RESOURCE_ATTRIBUTES: service.name=celery-service
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   depends_on:
  #     - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel_collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./stress_test/otel-collector.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger_ui
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # gRPC
      - "6831:6831/udp"

volumes:
  caddy_data:
  caddy_config:
