# ============================== Filebeat inputs ===============================
filebeat.inputs:
  - type: filestream
    id: proj2
    enabled: true
    paths:
      - /var/log/app.json

    # ── JSON 로그 파싱 ──
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true

# ============================== Processors =================================
processors:
  - add_host_metadata: { when.not.contains.tags: forwarded }
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

  # ── 필수 필드: timestamp 복사 ──
  - copy_fields:
      fields:
        - from: "app.meta.time"
          to:   "@timestamp"
      fail_on_error: false

  # ── 필수 필드: log level 복사 ──
  - copy_fields:
      fields:
        - from: "app.meta.level"
          to:   "log_level"
      fail_on_error: false

  # ── 사용자 정의 JSON 필드 복사 ──
  - copy_fields:
      fields:
        - from: "user.name"
          to:   "user"
      fail_on_error: false
  - copy_fields:
      fields:
        - from: "user.age"
          to:   "age"
      fail_on_error: false
  - copy_fields:
      fields:
        - from: "user.weight"
          to:   "weight"
      fail_on_error: false

  
  - drop_event:
      when:
        not:
          equals:
            user.age: "30"

  
  - add_tags:
      when:
        has_fields: ["_jsonparsefailure"]
      tags: ["_json_parse_error"]

# ================================= Outputs ===================================
output.logstash:
  hosts: ['127.0.0.1:5044']
  ssl.enabled: false

# ================================== Logging ===================================
logging.level: warning
logging.to_files: true